use failure::{Error, err_msg};

pub fn serve() -> Result<(), Error> {
    Ok(())
}
